# When master is updated, build and push to production S3

name: PERKO.DEV Deploy

# Controls when the action will run. Triggers the workflow on push to the master branch.
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: yarn install

      - name: Build for production
        run: yarn build

      # Sync with S3 and invalidate CloudFront
      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v1.1.2
        with:
          # Directory to deploy
          folder: ./dist/analog/public/
          # S3 Bucket
          bucket: ${{ secrets.S3_BUCKET }}
          # AWS CloudFront distribution ID
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
